# .readthedocs.yml
conda:
    file: docs/environment.yml

python:
<<<<<<< HEAD
    version: 3.5
=======
    version: 3.6
>>>>>>> nathanmlim-master
    setup_py_install: true
    extra_requirements:
    - tests
    - docs
