version: 1
disable_existing_loggers: False
formatters:
    debug:
        format: "%(levelname)s: [%(module)s.%(funcName)s] %(message)s"
    info:
        format: "%(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: debug
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: info
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

# loggers:
#     blues.ncmc:
#         level: DEBUG
#         handlers: [file_handler]
#         propagate: no
#     blues.storage:
#         level: INFO
#         handlers: [console]
#         propagate: no

root:
    level: DEBUG
    handlers: [file_handler]
