version: 1
disable_existing_loggers: False
formatters:
    debug:
        format: "%(levelname)s: [%(module)s.%(funcName)s] %(message)s"
    info:
        format: "%(message)s"

handlers:
    debug_console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: info
        stream: ext://sys.stdout

    # console:
    #     class: logging.StreamHandler
    #     level: INFO
    #     formatter: info
    #     stream: ext://sys.stdout

    # debug_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: DEBUG
    #     formatter: info
    #     filename: debug.log
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

    # info_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: INFO
    #     formatter: info
    #     filename: info.log
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

    # error_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: ERROR
    #     formatter: info
    #     filename: errors.log
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

# loggers:
#     blues.ncmc:
#         level: DEBUG
#         handlers: [debug_file_handler]
#         propagate: no
#     blues.storage:
#         level: INFO
#         handlers: [console]
#         propagate: no

root:
    level: DEBUG
    handlers: [debug_console]
