
# This file is automatically generated by setup.py
short_version = '0.2.3'
build_number = '0'
version = '0.2.3.dev0'
full_version = '0.2.3.dev0-7c20c28'
git_revision = '7c20c280223b53cb1ca7a77d629b30763d783ed4'
release = False
