
# This file is automatically generated by setup.py
short_version = '0.0.3'
version = '0.0.3.dev1'
full_version = '0.0.3.dev1-97d777a'
git_revision = '97d777a47e0e26560beeaf559cf120b983c28212'
release = False
