
# This file is automatically generated by setup.py
short_version = '0.2.2'
build_number = '1'
version = '0.2.2.dev1'
full_version = '0.2.2.dev1'
git_revision = '3ed0a2f892f6772ce32e9de90d24d2dea7b76eed'
release = True
