package:
  name: blues
  version: "0.0.1"

source:
  path: ../../

build:
  preserve_egg_dir: False
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmmtools
    - alchemy
    - mdtraj
    - openmm

  run:
    - python
    - setuptools
    - openmmtools
    - alchemy
    - mdtraj
    - openmm
    
test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
