package:
  name: blues
  version: 0.2.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0
  script: conda install --yes -c openeye/label/beta openeye-toolkits && python setup.py install

requirements:
  build:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
<<<<<<< HEAD
    - openmm >=7.1.1
    - parmed >=2.7.3
    - future
    - yank
=======
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml
>>>>>>> ee8d9b2c31e34c090808f7dbc5c0ca97b6ade195

  run:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
<<<<<<< HEAD
    - openmm >=7.1.1
    - parmed >=2.7.3
    - future
    - chemcoord
    - yank
=======
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml
>>>>>>> ee8d9b2c31e34c090808f7dbc5c0ca97b6ade195

test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
