package:
  name: blues
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - mdtraj
    - openmmtools
    - alchemy

test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
