# {% set data = load_setup_py_data() %}

package:
  name: blues
  #version: {{ data.get('version') }}
  #version: "{{ load_setup_py_data().version }}"
  #version: 0.2.2
  version: {{ environ['VERSION'] }}

source:
  #git_url: git@github.com/nathanmlim/blues.git
  #git_rev: {{ GIT_FULL_HASH }}
  #git_rev: {{ data.get('full_version') }}
  #git_url: https://github.com/nathanmlim/blues.git
  path: ../..

build:
  numbers: {{ GIT_DESCRIBE_NUMBER }}
  #number: {{ data.get('buildnum') }}
  noarch: generic
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}


test:
  requires:
    - pytest

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
