{% set short_version = '0.2.2' %}

package:
  name: blues
  version: {{ short_version }}

source:
  path : ../..

build:
  number: 0
  #script: conda activate test; python setup.py install --single-version-externally-managed --record=record.txt
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - pip

  build:
    - python
    - pytest
    - setuptools
    #- openmmtools <=0.15.0
    #- mdtraj <=1.9.1
    #- openmm <=7.2.2
    #- parmed <=3.0.1
    #- netcdf4 <=1.3.1
    #- pyyaml
    - pip

  run:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.15.0
    - mdtraj <=1.9.1
    - openmm <=7.2.2
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml

test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
