package:
  name: blues
  version: 0.1.3

source:
  path: ../..
build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.13.0
    - mdtraj <=1.9.1
    - openmm >=7.1.1
    - parmed >=2.7.3
    - future

  run:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.13.0
    - mdtraj <=1.9.1
    - openmm >=7.1.1
    - parmed >=2.7.3
    - future
    - chemcoord

test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
