package:
  name: blues
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path : ../..

  #build:
  #  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #string: py{{ CONDA_PY }}_{{ environ.get('GIT_BUILD_STR', '') }} # Ex. `py35_5_g6aaba2d`
  #string: py{{ CONDA_PY }}{{ environ.get('GIT_DESCRIBE_HASH', 'ERROR') }}_{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }} #Ex. `py35g6aaba2d_5`
  #script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]

  noarch: generic
  #  noarch: python

  script:
    - ${PYTHON}  -m pip install .


requirements:
  host:
    - python
    - setuptools
    - pip

  build:
    - python
    - pip
    - openeye-toolkits

  run:
    - python
    - pytest
    - setuptools
    - openmmtools==0.15.0
    - oeommtools # >=0.1.16
    - openeye-toolkits
    - mdtraj
    - openmm #>=7.2.2
    - parmed
    - netcdf4
    - hdf5
    - pyyaml
    - pip
    - numpy
    - cython
      

test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
