{% set build_number = '7.g53b29ae.dirty' %}
{% set short_version = '0.2.2' %}

package:
  name: blues
  version: {{ short_version }}

source:
  path : ../..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - pip

  build:
    - python
    - pytest
    - setuptools
    - openmmtools 0.15.0
    - mdtraj
    - openmm 7.2.2
    - parmed
    - netcdf4
    - pyyaml
    - pip

  run:
    - python
    - pytest
    - setuptools
    - openmmtools 0.15.0
    - mdtraj
    - openmm 7.2.2
    - parmed
    - netcdf4
    - pyyaml
    - pip

test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
