{% set short_version = '0.2.3' %}
{% set build_number = '0' %}
{% set version = '0.2.3.dev0' %}
{% set full_version = '0.2.3.dev0-47db981' %}
{% set git_revision = '47db9810a12718b29c5896dda38a8c4a1c99748e' %}
{% set release = 'False' %}

package:
  name: blues
  version: {{ short_version }}

source:
  git_rev: {{ git_revision }}
  git_url: https://github.com/nathanmlim/blues.git

build:
  number: {{ build_number }}
  noarch: generic
  preserve_egg_dir: True
  script: python setup.py install
  #script_env:
  #  - CONDA_BLD_FILE

requirements:
  build:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml
  run:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml
    # dependencies are defined in setup.py
    # {% for dep in data['install_requires'] %}
    # - {{ dep.lower() }}
    # {% endfor %}


test:
  requires:
    - pytest

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
