package:
  name: blues
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path : ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #string: py{{ CONDA_PY }}_{{ environ.get('GIT_BUILD_STR', '') }} # Ex. `py35_5_g6aaba2d`
  string: py{{ CONDA_PY }}{{ environ.get('GIT_DESCRIBE_HASH', 'ERROR') }}_{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }} #Ex. `py35g6aaba2d_5`
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - pip

  build:
    - python
    - pytest
    - setuptools
    - openmmtools >=0.15.0
    - mdtraj
    - openmm >=7.2.2
    - parmed
    - netcdf4
    - pyyaml
    - pip

  run:
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

test:
  requires:
    - pytest
  imports:
    - blues

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
