package:
  name: blues
  version: "0.0.1"

source:
  git_url: https://github.com/MobleyLab/blues

build:
  preserve_egg_dir: False
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - openmmtools
    - alchemy
    - mdtraj
    - openmm

  run:
    - python
    - setuptools
    - openmmtools
    - alchemy
    - mdtraj
    - openmm

test:
  requires:
    - pytest
    - openmmtools
    - alchemy
    - mdtraj
    - openmm
  imports:
    - blues
    - simtk

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
