package:
  name: blues
  version: "{{ load_setup_py_data().version }}"
  #version: 0.2.2
  #version: {{ environ['VERSION'] }}

source:
  #git_url: git@github.com/nathanmlim/blues.git
  #git_rev: {{ GIT_FULL_HASH }}
  #git_rev: {{ data.get('full_version') }}
  #git_url: https://github.com/nathanmlim/blues.git
  path: ../..

build:
  numbers: {{ GIT_DESCRIBE_NUMBER }}
  #number: {{ data.get('buildnum') }}
  noarch: generic
  preserve_egg_dir: True
  script: python setup.py install
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml

  run:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml

test:
  requires:
    - pytest

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
