package:
  name: blues
  version: 0.2.2
  #version: {{ environ['VERSION'] }}

source:
  path: ../..

build:
  number: 0
  noarch: generic
  preserve_egg_dir: True
  script: python setup.py install
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml

  run:
    - python
    - pytest
    - setuptools
    - openmmtools <=0.14.0
    - mdtraj <=1.9.1
    - openmm <=7.1.1
    - parmed <=3.0.1
    - netcdf4 <=1.3.1
    - pyyaml

test:
  requires:
    - pytest

about:
  home: https://github.com/mobleylab/blues
  license: MIT
  license_file: LICENSE
